

raw: raw.jpg

raw.jpg:
	echo "1. Run savage2 editor"
	echo "2. Load map you want to screenshot"
	echo "3. In console (Ctrl-F8) enter following:"
	echo "   scene_worldFarClip 100000"
	echo "   scene_farClip 100000"
	echo "4. In environment settings turn of fog (mode = None)"
	echo "5. Adjust camera to view from top point to the map."
	echo "6. Clean up all obstacles and big objects to make view clear" 
	echo "6. Orientate map as shown on minimap"
	echo "7. Press F12 to turn off toolbars"
	echo "8. Press Enter when you'll be ready ..."
	read line
	echo "Now click on the editor window to make screenshot"
	import raw.jpg


.PHONE: raw
.SILENT: raw.jpg